CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_KEYBOARD_NAME="AONAMI"
CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y

CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_WS2812=y
CONFIG_SPI=y
CONFIG_LED_STRIP=y