CONFIG_ZMK_USB_LOGGING=n
CONFIG_ZMK_KEYBOARD_NAME="AONAMI"
CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_POINTING=y

# Enable enhanced features
CONFIG_RGBLED_WIDGET=y
#CONN Blink Duration in milliseconds
CONFIG_RGBLED_WIDGET_CONN_BLINK_MS=750
CONFIG_RGBLED_WIDGET_INTERVAL_S_MS=1

CONFIG_RGBLED_WIDGET_BATTERY_BLINK_MS=1000
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=60

#CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE_COL=y
#CONFIG_RGBLED_WIDGET_LAYER_BLINK_MS=1000
#CONFIG_RGBLED_WIDGET_LAYER_0_COLOR_BLINK=6
#CONFIG_RGBLED_WIDGET_LAYER_1_COLOR_BLINK=7

CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=5
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=7


#CONFIG_RGBLED_WIDGET_CONN_COLOR_BT0=0
#CONFIG_RGBLED_WIDGET_CONN_COLOR_BT1=1
#CONFIG_RGBLED_WIDGET_CONN_COLOR_BT2=2
#CONFIG_RGBLED_WIDGET_CONN_COLOR_BT3=3
#CONFIG_RGBLED_WIDGET_CONN_COLOR_BT4=4

#CONFIG_RGBLED_WIDGET_WS2812=y
#CONFIG_RGBLED_WIDGET_LED_COUNT=3
#∫CONFIG_RGBLED_WIDGET_ANIMATIONS=y