manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    #- name: carrefinho                            # <--- add this
    #  url-base: https://github.com/carrefinho     # <--- and this
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar
    #- name: hitsmaxft  # <-- new entry
    #  url-base: https://github.com/hitsmaxft
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    #- name: prospector-zmk-module                 # <--- and these
    #  remote: carrefinho                          # <---
    #  revision: main                              # <---
    - name: zmk-rgbled-widget  # <-- new entry
      url: https://github.com/caksoylar/zmk-rgbled-widget
      revision: main
  self:
    path: config
